#!/bin/sh

# Program: Install
# Purpose: Install script for the Morse Book
# Assumptions: that this script is run from the directory which contains it

###--- Global Variables ---###

TOP=`pwd`
CONFIGURATION=Configuration

#####################################################################
###  MAIN LOGIC
#####################################################################

###--- Config setup and reading of non-include parameters --------###
if test ! -r $CONFIGURATION
then
    echo "Missing configuration file.  Please create $CONFIGURATION."
    exit 1
fi

exec 4<&0
exec < $CONFIGURATION
while read name value junk
do
    case "$name" in
        LIBDIRS)
            LIBDIRS=$value;;
        CONFIGPATH)
            CONFIGPATH=$value;;
        PYTHONPATH)
            python_path=$value;;
    esac
done
exec 0<&4

###--- Add link to configuration python executable ---------------###
if [ -h Configuration.pyc ]; then
    rm Configuration.pyc
fi
ln -s $CONFIGPATH Configuration.pyc

if [ -h python ]; then
    rm python
fi
ln -s $python_path python

###--- Untar the book files --------------------------------------###
tar xvfp morsebook.tar

###--- Generate the include directory ----------------------------###
mkdir -p include
gen_includes
cd www
ln -s ../include/ include
cd ..
chmod -f 750 *
chgrp -f www *
